// Keep this list aligned with the client-side hooks generated by Husky v9.
// `pre-auto-gc` is included even though it is not listed in Husky's documentation.
const hookNames = [
  'pre-commit',
  'pre-merge-commit',
  'prepare-commit-msg',
  'commit-msg',
  'post-commit',
  'applypatch-msg',
  'pre-applypatch',
  'post-applypatch',
  'pre-rebase',
  'post-rewrite',
  'post-checkout',
  'post-merge',
  'pre-push',
  'pre-auto-gc',
] as const;

type HookFileName = (typeof hookNames)[number] | 'runner';

// Generated shims live in `<hooks-directory>/_`. When a shim sources this
// dispatcher, `$0` still points to the shim, so the user hook is one level up.
const dispatcher = `#!/usr/bin/env sh

name=$(basename "$0")
dir=$(dirname "$(dirname "$0")")
hook="$dir/$name"

[ -f "$hook" ] || exit 0

sh -e "$hook" "$@"
status=$?
exit "$status"
`;

// Every generated Git hook sources the same dispatcher to keep runtime behavior
// consistent and make future initialization changes local to one file.
const shim = `#!/usr/bin/env sh
. "$(dirname "$0")/runner"
`;

export const createHookFiles = (): Record<HookFileName, string> => {
  const files: Record<string, string> = {
    runner: dispatcher,
  };

  for (const name of hookNames) {
    files[name] = shim;
  }

  return files as Record<HookFileName, string>;
};
