[workspace]
members = ["crates/rstack-binding", "crates/rstack-ignore"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
repository = "https://github.com/rstackjs/rstack-cli"
rust-version = "1.88"

[workspace.dependencies]
ignore = { version = "0.4.33", default-features = false }
napi = { version = "3.12.0", default-features = false, features = ["napi9"] }
napi-build = "2.4.0"
napi-derive = "3.6.2"
pathdiff = "0.2.3"
rstack-ignore = { path = "crates/rstack-ignore" }

[profile.release]
lto = true
strip = "symbols"
