packages:
  - packages/*
  - examples/*

allowBuilds:
  core-js: false
  simple-git-hooks: false

catalogMode: prefer

cleanupUnusedCatalogs: true

catalog:
  '@playwright/test': '^1.60.0'
  '@rsbuild/core': '^2.1.4'
  '@rsbuild/plugin-react': '^2.1.0'
  '@rslib/core': '^0.23.1'
  '@rslint/core': '^0.6.3'
  '@rstest/adapter-rsbuild': '^0.10.6'
  '@rstest/core': '^0.10.6'
  '@testing-library/dom': '^10.4.1'
  '@testing-library/jest-dom': '^6.9.1'
  '@testing-library/react': '^16.3.2'
  '@types/node': '^24.13.2'
  '@types/react': '^19.2.17'
  '@types/react-dom': '^19.2.3'
  'cspell-ban-words': '^0.0.4'
  'happy-dom': '^20.10.6'
  'lint-staged': '^16.4.0'
  'oxfmt': '^0.56.0'
  'playwright': '^1.60.0'
  'react': '^19.2.7'
  'react-dom': '^19.2.7'
  'typescript': '^6.0.3'

dedupePeers: true

autoInstallPeers: false

engineStrict: true

hoistPattern: []

# Reduce the risk of installing compromised packages
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@rspack/*'
  - '@rsbuild/*'
  - '@rslib/*'
  - '@rspress/*'
  - '@rstest/*'
  - '@rslint/*'
  - '@rstack-dev/doc-ui'
  - 'rsbuild-plugin-*'
  - '@swc/*'
  - 'heading-case'
