packages:
  - examples/*

allowBuilds:
  core-js: false
  simple-git-hooks: false

catalog:
  '@playwright/test': '^1.60.0'
  '@rsbuild/core': '^2.1.1'
  '@rsbuild/plugin-react': '^2.1.0'
  '@rslib/core': '^0.23.1'
  '@rslint/core': '^0.6.3'
  '@types/node': '^24.12.4'
  '@types/react': '^19.2.17'
  '@types/react-dom': '^19.2.3'
  'cac': '^7.0.0'
  'cspell-ban-words': '^0.0.4'
  'oxfmt': '^0.56.0'
  'playwright': '^1.60.0'
  'react': '^19.2.7'
  'react-dom': '^19.2.7'
  'typescript': '^6.0.3'
