/* auto-generated by NAPI-RS */
/* eslint-disable */
/** JavaScript-facing wrapper around the compiled Rust matcher. */
export declare class IgnoreMatcher {
  /** Compiles all pattern sources once and keeps the result for repeated path checks. */
  constructor(sources: Array<IgnoreSource>)
  /** Returns whether a file or directory is ignored by any source. */
  isIgnored(filePath: string, isDirectory: boolean): boolean
}

/** A Gitignore-compatible pattern source received from JavaScript. */
export interface IgnoreSource {
  /** Directory that patterns are resolved from. */
  rootPath: string
  /** Newline-delimited Gitignore patterns. */
  patterns: string
}
