// Keep this list aligned with the client-side hooks generated by Husky v9.
// `pre-auto-gc` is included even though it is not listed in Husky's documentation.
const hookNames = [
  'pre-commit',
  'pre-merge-commit',
  'prepare-commit-msg',
  'commit-msg',
  'post-commit',
  'applypatch-msg',
  'pre-applypatch',
  'post-applypatch',
  'pre-rebase',
  'post-rewrite',
  'post-checkout',
  'post-merge',
  'pre-push',
  'pre-auto-gc',
];

// Generated shims live in `<hooks-directory>/_`. When a shim sources this
// dispatcher, `$0` still points to the shim, so the user hook is one level up.
const dispatcher = `#!/usr/bin/env sh

name=$(basename "$0")
dir=$(dirname "$(dirname "$0")")
hook="$dir/$name"

[ -f "$hook" ] || exit 0

init="\${XDG_CONFIG_HOME:-$HOME/.config}/rstack/hooks-init.sh"
[ -f "$init" ] && . "$init"

[ "\${RSTACK_HOOKS-}" = "0" ] && exit 0
[ "\${RSTACK_HOOKS-}" = "2" ] && set -x

export PATH="node_modules/.bin:$PATH"

code=0
sh -e "$hook" "$@" || code=$?

[ "$code" = "0" ] || echo "Rstack - $name hook failed (code $code)"
[ "$code" = "127" ] && echo "Rstack - command not found in PATH=$PATH"
exit "$code"
`;

// Every generated Git hook sources the same dispatcher to keep runtime behavior
// consistent and make future initialization changes local to one file.
const shim = `#!/usr/bin/env sh
. "$(dirname "$0")/runner"
`;

export const createHookFiles = (): Record<string, string> => {
  const files: Record<string, string> = { runner: dispatcher };

  for (const name of hookNames) {
    files[name] = shim;
  }

  return files;
};
